# Generated by Django 2.2.7 on 2019-11-27 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cerveja', '0006_auto_20191127_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformidade', models.CharField(choices=[('sim', 'Conforme'), ('nao', 'Não Conforme')], default='Conformidade', max_length=3)),
                ('data_limite', models.DateField(default=datetime.date(2019, 12, 27), verbose_name='Limite para Analise')),
                ('analise_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cerveja.Cervejas')),
            ],
            options={
                'verbose_name': 'Analise',
                'verbose_name_plural': 'Analises',
                'ordering': ['data_limite'],
            },
        ),
    ]
