# Generated by Django 2.2.7 on 2019-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analises',
            name='analise_lote',
            field=models.IntegerField(default=0, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='analises',
            name='analise_quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
