# Generated by Django 2.2.7 on 2019-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_auto_20191127_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='analises',
            name='status',
            field=models.CharField(choices=[('1', 'À Analisar'), ('2', 'Em Análise'), ('3', 'Passou'), ('4', 'Descarte')], default='Status', max_length=1),
        ),
    ]
