# Generated by Django 2.2.7 on 2019-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_analises_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='conformidade',
            field=models.CharField(choices=[('Não Conforme - Em testes', 'Não Conforme - Em testes'), ('Conforme - Testado', 'Conforme - Testado'), ('Não Conforme - Testado', 'Não Conforme - Testado')], default='Conformidade', max_length=100),
        ),
        migrations.AlterField(
            model_name='analises',
            name='status',
            field=models.CharField(choices=[('Em Análise', 'Em Análise'), ('Passou', 'Passou'), ('Descarte', 'Descarte')], default='Status', max_length=100),
        ),
    ]
