# Generated by Django 2.2.7 on 2019-11-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cerveja', '0006_auto_20191127_0958'),
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_quant', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('saida_valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('saida_data', models.DateField(verbose_name='Data de Saída')),
                ('saida_cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidade.Cidades')),
                ('saida_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cerveja.Cervejas')),
            ],
            options={
                'verbose_name': 'Nota de Saida',
                'verbose_name_plural': 'Notas de Saida',
                'ordering': ['id'],
            },
        ),
    ]
