# Generated by Django 2.2.7 on 2019-11-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embalagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cervejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=100, verbose_name='Rotulo')),
                ('lote', models.IntegerField(default=0, verbose_name='Lote')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('fabric', models.DateField(blank=True)),
                ('validade', models.DateField(blank=True)),
                ('embalagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='embalagem.Embalagens')),
            ],
            options={
                'verbose_name': 'Cerveja',
                'verbose_name_plural': 'Cervejas',
                'ordering': ['lote'],
            },
        ),
    ]
