# Generated by Django 2.2.7 on 2019-11-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejas',
            name='conformidade',
            field=models.CharField(choices=[('sim', 'Conforme'), ('nao', 'Não Conforme')], default='Conformidade', max_length=3),
        ),
        migrations.AlterField(
            model_name='cervejas',
            name='fabric',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cervejas',
            name='validade',
            field=models.DateField(default=datetime.date(2020, 5, 25)),
        ),
    ]
