# Generated by Django 2.2.7 on 2019-11-27 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0004_cervejas_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='carga',
            field=models.DateField(default=datetime.date(2019, 12, 17), verbose_name='Prazo para saída'),
        ),
    ]
