# Generated by Django 2.2.7 on 2019-11-27 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0005_auto_20191127_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='validade',
            field=models.DateField(default=datetime.date(2020, 5, 25), verbose_name='Validade'),
        ),
    ]
