# Generated by Django 2.2.7 on 2019-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0006_auto_20191127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='conformidade',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('Não Conforme', 'Não Conforme')], default='Conformidade', max_length=100),
        ),
    ]
